name: Build and Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Tailwind CSS
        run: npm run build:css

      - name: Generate Firebase Config
        run: |
          cat > firebase-init.js << 'EOF'
          // Firebase configuration
          const firebaseConfig = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}"
          };

          // Initialize Firebase
          firebase.initializeApp(firebaseConfig);

          // Initialize services
          const auth = firebase.auth();
          const db = firebase.firestore();

          // Configure Firestore settings
          db.settings({
            cacheSizeBytes: firebase.firestore.CACHE_SIZE_UNLIMITED
          });

          // Enable offline persistence
          db.enablePersistence().catch((err) => {
            if (err.code == 'failed-precondition') {
              console.log('Multiple tabs open, persistence can only be enabled in one tab at a time.');
            } else if (err.code == 'unimplemented') {
              console.log('The current browser does not support persistence.');
            }
          });

          // Export for global use
          window.firebaseAuth = auth;
          window.firebaseDB = db;
          EOF

      - name: Create .nojekyll file
        run: touch .nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Validate HTML
        run: |
          npm install -g html-validate
          html-validate index.html

      - name: Check JavaScript syntax
        run: |
          npm install -g jshint
          jshint js/*.js
